"use client";

import { useEffect, useState } from "react";

const services = [
  ["01", "Electrical Works", "Professional electrical installation and maintenance.", "الأعمال الكهربائية", "تركيب وصيانة الأعمال الكهربائية باحترافية."],
  ["02", "Block Work & Masonry", "Professional block work and masonry construction.", "أعمال البلوك والبناء", "تنفيذ احترافي لأعمال البلوك والبناء."],
  ["03", "Plastering & Painting", "Interior and exterior plastering and painting services.", "اللياسة والدهان", "خدمات اللياسة والدهان الداخلي والخارجي."],
  ["04", "False Ceiling", "Gypsum and decorative false ceiling installation.", "الأسقف المستعارة", "تركيب أسقف الجبس والديكورات المستعارة."],
  ["05", "2D & 3D Modelling", "Professional architectural 2D drawings and 3D visualization.", "النمذجة ثنائية وثلاثية الأبعاد", "رسومات معمارية ثنائية الأبعاد وتصوّر ثلاثي الأبعاد باحترافية."],
  ["06", "Tiles • Marble • Granite", "Floor and wall finishing using premium materials.", "البلاط والرخام والجرانيت", "تشطيبات الأرضيات والجدران بمواد عالية الجودة."],
  ["07", "Architecture & Structural Detailing", "Architectural design and structural detailing solutions.", "التفاصيل المعمارية والإنشائية", "حلول التصميم المعماري والتفاصيل الإنشائية."],
  ["08", "MEP Works", "Mechanical, Electrical and Plumbing systems.", "أعمال MEP", "أنظمة الميكانيكا والكهرباء والسباكة."],
  ["09", "Electromechanical Equipment Installation & Maintenance", "Installation and maintenance of electromechanical equipment.", "تركيب وصيانة المعدات الكهروميكانيكية", "تركيب وصيانة المعدات الكهروميكانيكية."],
] as const;

const quick = [
  ["Block Work & Masonry", "أعمال البلوك والبناء"], ["Plastering & Painting", "اللياسة والدهان"], ["False Ceiling", "الأسقف المستعارة"], ["2D & 3D Modelling", "النمذجة ثنائية وثلاثية الأبعاد"], ["Tiles / Marble / Granite", "البلاط والرخام والجرانيت"], ["Structural Detailing", "التفاصيل الإنشائية"], ["MEP Works", "أعمال MEP"], ["Core Cutting", "قص الخرسانة"], ["Grout Injection", "حقن الجراوت"], ["Electromechanical", "الأعمال الكهروميكانيكية"],
] as const;
const projects = [
  ["Steel Frame", "الهيكل الفولاذي"], ["MEP Installation", "تركيب أنظمة MEP"], ["Architectural Finish", "التشطيبات المعمارية"], ["Precision Electrical", "الأعمال الكهربائية الدقيقة"], ["Commercial Fit-Out", "التجهيزات التجارية"], ["Structural Detailing", "التفاصيل الإنشائية"], ["Ceiling Works", "أعمال الأسقف"], ["Civil Maintenance", "الصيانة المدنية"], ["Technical Solutions", "الحلول التقنية"],
] as const;

export default function Home() {
  const [arabic, setArabic] = useState(false);
  const [menu, setMenu] = useState(false);
  const [lightbox, setLightbox] = useState<number | null>(null);
  const pick = (english: string, ar: string) => arabic ? ar : english;
  useEffect(() => {
    const onScroll = () => document.body.classList.toggle("scrolled", window.scrollY > 32);
    onScroll(); window.addEventListener("scroll", onScroll); return () => window.removeEventListener("scroll", onScroll);
  }, []);
  const toggleLanguage = () => { setArabic((value) => !value); setMenu(false); };

  return <main dir={arabic ? "rtl" : "ltr"} lang={arabic ? "ar" : "en"} className={arabic ? "arabic" : ""}>
    <nav className="nav"><a href="#home" className="brand"><img src="/logo.png" alt="Island Technical Services"/><span>ISLAND <small>ENGINEERING EXCELLENCE</small></span></a><button className="menu" onClick={() => setMenu(!menu)} aria-label={pick("Toggle menu", "فتح القائمة")}>☰</button><div className={menu ? "links open" : "links"}><a href="#home">{pick("Home", "الرئيسية")}</a><a href="#services">{pick("Services", "الخدمات")}</a><a href="#projects">{pick("Projects", "المشاريع")}</a><a href="#contact">{pick("Contact", "اتصل بنا")}</a><button className="language" onClick={toggleLanguage} aria-label={pick("Switch to Arabic", "التبديل إلى الإنجليزية")}>{arabic ? "العربية / EN" : "EN / العربية"}</button></div></nav>
    <section id="home" className="hero"><div className="hero-image"/><div className="grid"/><div className="orb orb1"/><div className="orb orb2"/><div className="hero-copy"><p className="eyebrow">{pick("UAE / ENGINEERING & TECHNICAL SERVICES", "الإمارات / خدمات هندسية وتقنية")}</p><h1>{pick("Professional Technical Services in UAE", "خدمات تقنية احترافية في الإمارات")}</h1><p className="intro">{pick("We provide Electrical, Plumbing, HVAC, Civil Maintenance, and Complete Technical Solutions with professional quality and experienced engineers.", "نقدم أعمال الكهرباء والسباكة والتكييف والصيانة المدنية والحلول التقنية المتكاملة بجودة احترافية وفريق من المهندسين ذوي الخبرة.")}</p><div className="actions"><a className="button primary" href="https://wa.me/971541518181">{pick("Contact on WhatsApp", "تواصل عبر واتساب")} <b>↗</b></a><a className="button" href="#services">{pick("Our Services", "خدماتنا")} <b>↓</b></a></div></div><div className="frame" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div><div className="scroll-note">{pick("SCROLL TO EXPLORE", "مرر للاستكشاف")} <span/></div></section>
    <section id="services" className="section services"><div className="section-head"><p className="eyebrow">{pick("01 / OUR EXPERTISE", "01 / خبراتنا")}</p><h2>{pick("Technical mastery.", "خبرة تقنية.")}<br/><em>{pick("Built to last.", "مصممة لتدوم.")}</em></h2><p>{pick("Comprehensive, exacting services for projects where every dimension matters.", "خدمات شاملة ودقيقة للمشاريع التي تهم فيها كل التفاصيل.")}</p></div><div className="service-strip">{quick.map(([en, ar], i) => <article className="quick-card" key={en}><span>0{i + 1}</span><h3>{pick(en, ar)}</h3><b>↗</b></article>)}</div></section>
    <section className="values"><p className="eyebrow">{pick("02 / WHY ISLAND", "02 / لماذا آيلاند")}</p><div className="value-grid">{[["⚡", "Professional Team", "Skilled specialists for every discipline.", "فريق محترف", "مختصون مهرة لكل مجال."], ["🛠", "Quality Work", "Precision materials, rigorous execution.", "عمل بجودة عالية", "مواد دقيقة وتنفيذ متقن."], ["⏱", "Fast Response", "Responsive support when it counts.", "استجابة سريعة", "دعم سريع عندما تحتاجه."], ["✓", "Customer Satisfaction", "Delivered with care, safety and clarity.", "رضا العملاء", "تنفيذ بعناية وسلامة ووضوح."]].map(([icon, enTitle, enCopy, arTitle, arCopy], i) => <article key={enTitle}><span>{icon}</span><b>0{i + 1}</b><h3>{pick(enTitle, arTitle)}</h3><p>{pick(enCopy, arCopy)}</p></article>)}</div></section>
    <section className="about"><div className="about-visual"><div className="about-lines"/></div><div className="about-copy"><p className="eyebrow">{pick("03 / ABOUT THE STUDIO", "03 / عن الشركة")}</p><h2>{pick("Engineering clarity for the ", "وضوح هندسي لعالم ")}<em>{pick("built world.", "البناء.")}</em></h2><p>{pick("Island Technical Services is a UAE-based company specializing in electrical works, plumbing, HVAC, civil maintenance, and complete technical solutions. We are committed to quality, safety, and customer satisfaction.", "آيلاند للخدمات التقنية هي شركة مقرها الإمارات متخصصة في الأعمال الكهربائية والسباكة والتكييف والصيانة المدنية والحلول التقنية المتكاملة. نحن ملتزمون بالجودة والسلامة ورضا العملاء.")}</p></div></section>
    <section id="services-detail" className="section detail"><div className="section-head"><p className="eyebrow">{pick("04 / CAPABILITIES", "04 / قدراتنا")}</p><h2>{pick("Every technical", "كل تفصيلة")}<br/><em>{pick("detail considered.", "تقنية مدروسة.")}</em></h2></div><div className="detail-grid">{services.map(([number, enTitle, enCopy, arTitle, arCopy]) => <article key={enTitle} className="detail-card"><span>{number}</span><h3>{pick(enTitle, arTitle)}</h3><p>{pick(enCopy, arCopy)}</p><i>↗</i></article>)}</div></section>
    <section id="projects" className="projects"><div className="project-head"><div><p className="eyebrow">{pick("05 / SELECTED PROJECTS", "05 / مشاريع مختارة")}</p><h2>{pick("Work with a ", "أعمال بمعيار ")}<em>{pick("standard.", "متميز.")}</em></h2></div><p>{pick("From the backbone of a structure to its final finish — each project is a signature of precision.", "من أساس الهيكل إلى اللمسات النهائية، كل مشروع يعكس دقتنا.")}</p></div><div className="gallery">{projects.map(([en, ar], i) => <button key={en} className={`project project-${i + 1}`} onClick={() => setLightbox(i)} aria-label={pick(`Open ${en} project`, `فتح مشروع ${ar}`)}><div><span>2026 / 0{i + 1}</span><h3>{pick(en, ar)}</h3><b>{pick("View project", "عرض المشروع")} ↗</b></div></button>)}</div></section>
    <section id="contact" className="contact"><div><p className="eyebrow">{pick("06 / START A PROJECT", "06 / ابدأ مشروعك")}</p><h2>{pick("Let’s build something ", "لنصنع شيئاً ")}<em>{pick("exceptional.", "استثنائياً.")}</em></h2><a className="contact-mail" href="mailto:islandtech.ae@gmail.com">islandtech.ae@gmail.com <b>↗</b></a></div><div className="contact-info"><p><span>{pick("WHATSAPP", "واتساب")}</span><a href="https://wa.me/971541518181">+971 54 151 8181</a></p><p><span>{pick("OFFICE", "المكتب")}</span><a href="tel:+97167655006">+971 6 765 5006</a></p><p><span>{pick("LOCATION", "الموقع")}</span>{pick("United Arab Emirates", "الإمارات العربية المتحدة")}</p></div><div className="map"><iframe title="Island Technical Services location" src="https://www.google.com/maps?q=Dubai,UAE&output=embed" loading="lazy"/></div></section>
    <footer><div className="footer-brand">ISLAND <span>TECHNICAL SERVICES</span></div><p>{pick("Engineering Excellence", "التميز الهندسي")}</p><small>© 2026 Island Technical Services. {pick("All Rights Reserved.", "جميع الحقوق محفوظة.")}</small></footer>
    <a className="whatsapp" href="https://wa.me/971541518181" aria-label={pick("Chat on WhatsApp", "تواصل عبر واتساب")}><span>{pick("WhatsApp", "واتساب")}</span></a>
    {lightbox !== null && <div className="lightbox" role="dialog" aria-modal="true" onClick={() => setLightbox(null)}><div className={`lightbox-card project-${lightbox + 1}`} onClick={(e) => e.stopPropagation()}><button onClick={() => setLightbox(null)} aria-label={pick("Close", "إغلاق")}>×</button><p>ISLAND TECHNICAL SERVICES / 2026</p><h2>{pick(projects[lightbox][0], projects[lightbox][1])}</h2><span>{pick("Engineering Excellence", "التميز الهندسي")}</span></div></div>}
  </main>;
}
